build_script:
- ps: >-
    $version = (Get-Content .\TMDbLib\project.json | ConvertFrom-Json).version

    Update-AppveyorBuild -Version "$version build $env:APPVEYOR_BUILD_NUMBER"
- ps: >-
    # Core

    dotnet restore
- ps: >-
    # Library

    dotnet pack -c Release -o Nuget\ TMDbLib
- ps: >-
    # Test app

    dotnet build -c Release TestApplication
- ps: >-
    # Tests

    dotnet build -c Release TMDbLibTests
test: off
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget