image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\TMDbLib\TMDbLib.csproj)

    $version = $doc.Project.PropertyGroup.VersionPrefix

    Update-AppveyorBuild -Version "$version build $env:APPVEYOR_BUILD_NUMBER"
- ps: # Core
- ps: dotnet restore
- ps: # Library
- ps: dotnet pack -c Release -o Nuget\ TMDbLib
- ps: # Test app
- ps: dotnet build -c Release TestApplication
- ps: # Tests
- ps: dotnet build -c Release TMDbLibTests
test: off
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget